### ISSUE TITLE
Compatibility problem on Firefox

### ISSUE THREAD

**Issue by antoinentl** [HadrienGardeur/webpub-viewer#1]
## Observation

When I look at [https://proto.myopds.com/?manifest=true&href=https://proto.myopds.com/manifest/mobydick.epub/manifest.json&document=https://proto.myopds.com/assets/mobydick.epub/main0.xml](https://proto.myopds.com/?manifest=true&href=https://proto.myopds.com/manifest/mobydick.epub/manifest.json&document=https://proto.myopds.com/assets/mobydick.epub/main0.xml) on the Mozilla Firefox browser (Ubuntu + Android), the content section have a height of 114px, so it's not possible to read the text.
## Expectation

The content must fit the screen height.
## Steps to reproduce the problem

Go to this URL on Firefox : [https://proto.myopds.com/?manifest=true&href=https://proto.myopds.com/manifest/mobydick.epub/manifest.json&document=https://proto.myopds.com/assets/mobydick.epub/main0.xml](https://proto.myopds.com/?manifest=true&href=https://proto.myopds.com/manifest/mobydick.epub/manifest.json&document=https://proto.myopds.com/assets/mobydick.epub/main0.xml)

**Comment by HadrienGardeur** [comment]
Yes, I'm aware of this problem too.

I never work with iframes, so I have limited knowledge regarding automatically scaling their height. To solve this issue, I rely on JS to dynamically resize the iframe height, but it doesn't seem to work on Firefox even though it should.

Works fine on Chrome (desktop & mobile) though.

**Comment by HadrienGardeur** [comment]
So, I think I figured this out...

Chrome and Firefox return different values for document.body.scrollHeight. While Chrome scrolls the whole window, FF doesn't.

I've changed the code to window.innerHeight instead and it seems to work fine on both browsers.

Here's a demo: https://hadriengardeur.github.io/webpub-manifest/examples/viewer/?manifest=true&href=https://proto.myopds.com/manifest/mobydick.epub/manifest.json

Can you confirm that it works fine for you @antoinentl?

**Comment by antoinentl** [comment]
Perfect! And it works on Opera! (and on Safari?...)

**Comment by HadrienGardeur** [comment]
Safari doesn't support `fetch`, I'll need to add a polyfill for Safari support.

http://caniuse.com/#feat=fetch

**Comment by antoinentl** [comment]
Ho yeah I forgot it...
