### ISSUE TITLE
Navigate with URLs

### ISSUE THREAD

**Issue by antoinentl** [HadrienGardeur/webpub-viewer#2]
## Observation

When I read [https://proto.myopds.com/?manifest=true&href=https://proto.myopds.com/manifest/mobydick.epub/manifest.json&document=https://proto.myopds.com/assets/mobydick.epub/title.xml](https://proto.myopds.com/?manifest=true&href=https://proto.myopds.com/manifest/mobydick.epub/manifest.json&document=https://proto.myopds.com/assets/mobydick.epub/title.xml), I read different pages/chapters. When I go back on a URL like [that](https://proto.myopds.com/?manifest=true&href=https://proto.myopds.com/manifest/mobydick.epub/manifest.json&document=https://proto.myopds.com/assets/mobydick.epub/main2.xml), I'm always redirected to the [start/cover page](https://proto.myopds.com/?manifest=true&href=https://proto.myopds.com/manifest/mobydick.epub/manifest.json&document=https://proto.myopds.com/assets/mobydick.epub/main2.xml)
## Expectation

I want to return to the page I want with a URL. 
## Steps to reproduce the problem

Refresh any page/chapter, expect the cover page.

**Comment by HadrienGardeur** [comment]
That's planned too, for now I've commented the code that refreshes the URI, I'll add it again once the navigation to a specific document is implemented.

**Comment by antoinentl** [comment]
Ok nice!

**Comment by HadrienGardeur** [comment]
Re-opened as an enhancement.

**Comment by HadrienGardeur** [comment]
@antoinentl example at https://hadriengardeur.github.io/webpub-manifest/examples/viewer
