### ISSUE TITLE
Add an access to the TOC

### ISSUE THREAD

**Issue by antoinentl** [HadrienGardeur/webpub-viewer#3]
## Observation

I don't find an access to the TOC (table of contents) on every page. (Note: perhaps this function match with non-fiction ebooks).
## Expectation

Add an access to the TOC, besides the `previous` and `next` elements of navigation. (In viewer.js I guess, with the informations from the toc.ncx file on the EPUB.)
## Steps to reproduce the problem

Try to go to a chapter without _flip_ the different pages/chapters.

**Comment by HadrienGardeur** [comment]
This can be extracted from either `spine` or `resources` by looking at rel="contents".

We're working strictly with a Web Publication Manifest here, for the NCX case, file an issue on https://github.com/banux/webpub-streamer

**Comment by HadrienGardeur** [comment]
@antoinentl example at https://hadriengardeur.github.io/webpub-manifest/examples/viewer
